module.exports = {
    Type: [ {
        id: 0,
        name: "MF1-S50"
    }, {
        id: 1,
        name: "MF1-S70"
    }, {
        id: 2,
        name: "HD-H4100"
    } ],
    IDHz: [ {
        id: 0,
        name: "125Khz"
    }, {
        id: 1,
        name: "134Khz"
    }, {
        id: 2,
        name: "250Khz"
    }, {
        id: 3,
        name: "300Khz"
    }, {
        id: 4,
        name: "375Khz"
    }, {
        id: 5,
        name: "500Khz"
    } ],
    ICHZ: [ {
        id: 0,
        name: "13.56Mhz"
    } ],
    FullHz: [ {
        id: "01",
        name: "125Khz"
    }, {
        id: "02",
        name: "134Khz"
    }, {
        id: "03",
        name: "250Khz"
    }, {
        id: "04",
        name: "300Khz"
    }, {
        id: "05",
        name: "375Khz"
    }, {
        id: "06",
        name: "500Khz"
    }, {
        id: "07",
        name: "625Khz"
    }, {
        id: "08",
        name: "750Khz"
    }, {
        id: "09",
        name: "875Khz"
    }, {
        id: "0A",
        name: "1000Khz"
    }, {
        id: "0B",
        name: "13.56Mhz"
    } ],
    FullCardType: [ {
        id: "01",
        name: "T5577"
    }, {
        id: "02",
        name: "MF1-S70"
    }, {
        id: "03",
        name: "EM4305"
    }, {
        id: "04",
        name: "MF1-S50"
    }, {
        id: "05",
        name: "AT5588"
    }, {
        id: "06",
        name: "EM4308"
    }, {
        id: "07",
        name: "MF-AUID"
    }, {
        id: "08",
        name: "ID-H4100"
    }, {
        id: "09",
        name: "HID"
    }, {
        id: "0A",
        name: "Ntag215"
    } ],
    hex_array: [ {
        key: 0,
        val: "0000"
    }, {
        key: 1,
        val: "0001"
    }, {
        key: 2,
        val: "0010"
    }, {
        key: 3,
        val: "0011"
    }, {
        key: 4,
        val: "0100"
    }, {
        key: 5,
        val: "0101"
    }, {
        key: 6,
        val: "0110"
    }, {
        key: 7,
        val: "0111"
    }, {
        key: 8,
        val: "1000"
    }, {
        key: 9,
        val: "1001"
    }, {
        key: "a",
        val: "1010"
    }, {
        key: "b",
        val: "1011"
    }, {
        key: "c",
        val: "1100"
    }, {
        key: "d",
        val: "1101"
    }, {
        key: "e",
        val: "1110"
    }, {
        key: "f",
        val: "1111"
    } ],
    hex_array_big: [ {
        key: 0,
        val: "0000"
    }, {
        key: 1,
        val: "1000"
    }, {
        key: 2,
        val: "0100"
    }, {
        key: 3,
        val: "1100"
    }, {
        key: 4,
        val: "0010"
    }, {
        key: 5,
        val: "1010"
    }, {
        key: 6,
        val: "0110"
    }, {
        key: 7,
        val: "1110"
    }, {
        key: 8,
        val: "0001"
    }, {
        key: 9,
        val: "1001"
    }, {
        key: "a",
        val: "0101"
    }, {
        key: "b",
        val: "1101"
    }, {
        key: "c",
        val: "0011"
    }, {
        key: "d",
        val: "1011"
    }, {
        key: "e",
        val: "0111"
    }, {
        key: "f",
        val: "1111"
    } ]
};